"minecraft:story/mine_stone" = 0.5
"minecraft:story/upgrade_tools" = 0.5
"minecraft:story/smelt_iron" = 1.0
"minecraft:story/obtain_armor" = 1.0
"minecraft:story/lava_bucket" = 1.0
"minecraft:story/iron_tools" = 1.0
"minecraft:story/deflect_arrow" = 1.0
"minecraft:story/form_obsidian" = 1.0
"minecraft:story/mine_diamond" = 2.0
"minecraft:story/enter_the_nether" = 2.0
"minecraft:story/shiny_gear" = 5.0
"minecraft:story/enchant_item" = 2.0
"minecraft:story/cure_zombie_villager" = 4.0
"minecraft:story/follow_ender_eye" = 3.0
"minecraft:story/enter_the_end" = 2.0
"minecraft:nether/return_to_sender" = 3.0
"minecraft:nether/find_bastion" = 3.0
"minecraft:nether/obtain_ancient_debris" = 4.0
"minecraft:nether/fast_travel" = 5.0
"minecraft:nether/find_fortress" = 3.0
"minecraft:nether/obtain_crying_obsidian" = 1.0
"minecraft:nether/distract_piglin" = 2.0
"minecraft:nether/ride_strider" = 2.0
"minecraft:nether/uneasy_alliance" = 5.0
"minecraft:nether/loot_bastion" = 3.0
"minecraft:nether/use_lodestone" = 1.0
"minecraft:nether/netherite_armor" = 10.0
"minecraft:nether/get_wither_skull" = 5.0
"minecraft:nether/obtain_blaze_rod" = 2.0
"minecraft:nether/charge_respawn_anchor" = 2.0
"minecraft:nether/ride_strider_in_overworld_lava" = 3.0
"minecraft:nether/explore_nether" = 5.0
"minecraft:nether/summon_wither" = 3.0
"minecraft:nether/brew_potion" = 1.0
"minecraft:nether/create_beacon" = 2.0
"minecraft:nether/all_potions" = 5.0
"minecraft:nether/use_soul_speed" = 0.5
"minecraft:nether/create_full_beacon" = 7.0
"minecraft:nether/all_effects" = 35.0
"minecraft:end/kill_dragon" = 5.0
"minecraft:end/dragon_egg" = 5.0
"minecraft:end/enter_end_gateway" = 2.0
"minecraft:end/respawn_dragon" = 5.0
"minecraft:end/dragon_breath" = 2.0
"minecraft:end/find_end_city" = 4.0
"minecraft:end/elytra" = 8.0
"minecraft:end/levitate" = 4.0
"minecraft:adventure/voluntary_exile" = 2.0
"minecraft:adventure/spyglass_at_parrot" = 2.0
"minecraft:adventure/kill_a_mob" = 1.0
"minecraft:adventure/read_power_from_chiseled_bookshelf" = 2.0
"minecraft:adventure/trade" = 2.0
"minecraft:adventure/trim_with_any_armor_pattern" = 2.0
"minecraft:adventure/honey_block_slide" = 2.0
"minecraft:adventure/ol_betsy" = 1.0
"minecraft:adventure/lightning_rod_with_villager_no_fire" = 3.0
"minecraft:adventure/fall_from_world_height" = 4.0
"minecraft:adventure/salvage_sherd" = 3.0
"minecraft:adventure/avoid_vibration" = 2.0
"minecraft:adventure/sleep_in_bed" = 1.0
"minecraft:adventure/hero_of_the_village" = 10.0
"minecraft:adventure/spyglass_at_ghast" = 2.0
"minecraft:adventure/throw_trident" = 2.0
"minecraft:adventure/kill_mob_near_sculk_catalyst" = 2.0
"minecraft:adventure/shoot_arrow" = 1.0
"minecraft:adventure/kill_all_mobs" = 15.0
"minecraft:adventure/totem_of_undying" = 5.0
"minecraft:adventure/summon_iron_golem" = 3.0
"minecraft:adventure/trade_at_world_height" = 3.0
"minecraft:adventure/trim_with_all_exclusive_armor_patterns" = 15.0
"minecraft:adventure/two_birds_one_arrow" = 3.0
"minecraft:adventure/whos_the_pillager_now" = 2.0
"minecraft:adventure/arbalistic" = 6.0
"minecraft:adventure/craft_decorated_pot_using_only_sherds" = 3.0
"minecraft:adventure/adventuring_time" = 30.0
"minecraft:adventure/play_jukebox_in_meadows" = 3.0
"minecraft:adventure/walk_on_powder_snow_with_leather_boots" = 2.0
"minecraft:adventure/spyglass_at_dragon" = 2.0
"minecraft:adventure/very_very_frightening" = 2.0
"minecraft:adventure/sniper_duel" = 4.0
"minecraft:adventure/bullseye" = 4.0
"minecraft:husbandry/safely_harvest_honey" = 2.0
"minecraft:husbandry/breed_an_animal" = 2.0
"minecraft:husbandry/allay_deliver_item_to_player" = 3.0
"minecraft:husbandry/tame_an_animal" = 2.0
"minecraft:husbandry/make_a_sign_glow" = 1.0
"minecraft:husbandry/fishy_business" = 1.0
"minecraft:husbandry/silk_touch_nest" = 3.0
"minecraft:husbandry/tadpole_in_a_bucket" = 3.0
"minecraft:husbandry/obtain_sniffer_egg" = 5.0
"minecraft:husbandry/plant_seed" = 0.5
"minecraft:husbandry/wax_on" = 1.0
"minecraft:husbandry/bred_all_animals" = 20.0
"minecraft:husbandry/allay_deliver_cake_to_note_block" = 2.0
"minecraft:husbandry/complete_catalogue" = 17.0
"minecraft:husbandry/tactical_fishing" = 1.0
"minecraft:husbandry/leash_all_frog_variants" = 5.0
"minecraft:husbandry/feed_snifflet" = 4.0
"minecraft:husbandry/balanced_diet" = 12.0
"minecraft:husbandry/obtain_netherite_hoe" = 6.0
"minecraft:husbandry/wax_off" = 0.5
"minecraft:husbandry/axolotl_in_a_bucket" = 3.0
"minecraft:husbandry/froglights" = 5.0
"minecraft:husbandry/plant_any_sniffer_seed" = 5.0
"minecraft:husbandry/kill_axolotl_target" = 3.0
